### ISSUE TITLE
User and UserAuth Entity prepration (Model)

### ISSUE THREAD

**Issue by shubham-8551** [Arc-i-Tech/Arc-i-Tech.github.io#159]
**### User and Auth acceptance criteria:**

1. Use entity annotation and table name annotation 
2. follow the database entity names and datatypes
3. it should be used for naming convenience  
4. use the setter and getter, toString, and Constructor ( required parameterized and non-parameterized)
5. create the proper indentation and format
6. create the class name as User and UserAuth

**Comment by ajayg2808** [comment]
Resolved by #162
