### ISSUE TITLE
Task-Auto assign Pull Request

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#204]
## Task Summary
- Pull Request should have assignee as to linked/ closing issues.

## Acceptance Criteria
- [ ] Whenever Pull Request it must get assigned
- [ ] For existing Pull Request assignee must be from closing reference issues.

## Subtasks
- NA
  
## Related Issues
- NA

## Additional Notes
- NA

**Comment by serv-cat** [comment]
Pull Request #206 closed without merging.

**Comment by serv-cat** [comment]
Closed by #207
