### ISSUE TITLE
Task-Close Issue when PR is merged/ closed

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#205]
## Task Summary
- Closing reference `Issues` of `Pull Request` should get closed when `Pull Request` is `merged`.
- If not merged comment on Issue saying PR is closed.

## Acceptance Criteria
- [ ] The issue must be closed when PR merges.
- [ ] Comment on Issue when PR is closed but not merged.

## Subtasks
- NA
  
## Related Issues
- NA

## Additional Notes
- NA

**Comment by serv-cat** [comment]
Pull Request #206 closed without merging.

**Comment by serv-cat** [comment]
Linked Pull Request: #206 closed without merging.<br>Have look into it.

**Comment by serv-cat** [comment]
Closed by #206
