### ISSUE TITLE
Miscellaneous/ small updates

### ISSUE THREAD

**Issue by ajayg2808** [Arc-i-Tech/Arc-i-Tech.github.io#47]
- [x] Carousel Buttons and transition
- [x] Link should not open a new tab. Social Media links can open in new tab.
- [x] ICONs for project card/ profile
- [x] Carousel not working on small screen (Desktop mode in Mobile) ![Reference screenshot](https://user-images.githubusercontent.com/34316783/218469697-61557a76-b21d-45e9-a26a-641d38e0fee0.jpg)
- [x] Status bar not working on small screen (Desktop mode in Mobile)![reference screenshot 1](https://user-images.githubusercontent.com/34316783/218470031-916d62f1-364c-48f8-abca-86f0014f8ae6.jpg)![reference screenshot 2](https://user-images.githubusercontent.com/34316783/218470127-a8cedaf0-0464-436e-9577-94f02ada3883.jpg)
- [x] Favicon for website

**Comment by ajstyle2410** [comment]
About Page Not  added

**Comment by ajstyle2410** [comment]
Corosel button are cleared but  transition..

**Comment by ajayg2808** [comment]
> About Page Not added then link are point the aboutUs id then dose not open another page

There is section with id="about-us" in `index.html` itself.

**Comment by ajayg2808** [comment]
> Corosel button are cleared but transition..

Currently don't go for transition.
The carousel left and right button background color is not as good. Need to change it w.r.t the carousel design.
